workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      android_signing:
        - keystore_reference 
      groups:
        - google_play  
      vars:
        PACKAGE_NAME: "com.dermavisionai"  
        # You might want to update this to the latest stable Node.js version
        node: 16.14.2   
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        # Or 'main' or your primary branch
        - pattern: develop  
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Set up android/app/build.gradle
        script: | 
          # If you have a custom build.gradle
          mv ./support-files/build.gradle android/app 
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "<span class="math-inline">CM\_BUILD\_DIR/android/local\.properties"
\- name\: Build Android release
script\: \|
